
# Session variables:
VAR_SESSION_SORT_METHOD_TAG: str = "SESSION_SORT_METHOD"
VAR_SESSION_SORT_METHOD_SUIT: str = f"{VAR_SESSION_SORT_METHOD_TAG}_SUIT"
VAR_SESSION_SORT_METHOD_VALUE: str = f"{VAR_SESSION_SORT_METHOD_TAG}_VALUE"
VAR_SESSION_SORT_METHOD_ADDED: str = f"{VAR_SESSION_SORT_METHOD_TAG}_ADDED"

# Card suit variables:
VAR_CARD_SUIT_TAG: str = "CARD_SUIT"
VAR_CARD_SUIT_NOT_SET: str = f"{VAR_CARD_SUIT_TAG}_NOTSET"
VAR_CARD_SUIT_HEARTS: str = f"{VAR_CARD_SUIT_TAG}_HEARTS"
VAR_CARD_SUIT_DIAMONDS: str = f"{VAR_CARD_SUIT_TAG}_DIAMONDS"
VAR_CARD_SUIT_CLUBS: str = f"{VAR_CARD_SUIT_TAG}_CLUBS"
VAR_CARD_SUIT_SPADES: str = f"{VAR_CARD_SUIT_TAG}_SPADES"

# Card suit color variables:
VAR_CARD_SUIT_COLOR_TAG: str = "CARD_SUIT_COLOR"
VAR_CARD_SUIT_COLOR_RED: str = f"{VAR_CARD_SUIT_COLOR_TAG}_RED"
VAR_CARD_SUIT_COLOR_BLACK: str = f"{VAR_CARD_SUIT_COLOR_TAG}_BLACK"

# Card suit unicode variables:
VAR_CARD_SUIT_HEARTS_UNICODE: str = f"{VAR_CARD_SUIT_TAG}_HEARTS"
VAR_CARD_SUIT_DIAMONDS_UNICODE: str = f"{VAR_CARD_SUIT_TAG}_DIAMONDS"
VAR_CARD_SUIT_CLUBS_UNICODE: str = f"{VAR_CARD_SUIT_TAG}_CLUBS"
VAR_CARD_SUIT_SPADES_UNICODE: str = f"{VAR_CARD_SUIT_TAG}_SPADES"

# Card type variables:
VAR_CARD_TYPE_TAG: str = "CARD_TYPE"
VAR_CARD_TYPE_NOT_SET: str = f"{VAR_CARD_TYPE_TAG}_NOTSET"
VAR_CARD_TYPE_SIX: str = f"{VAR_CARD_TYPE_TAG}_SIX"
VAR_CARD_TYPE_SEVEN: str = f"{VAR_CARD_TYPE_TAG}_SEVEN"
VAR_CARD_TYPE_EIGHT: str = f"{VAR_CARD_TYPE_TAG}_EIGHT"
VAR_CARD_TYPE_NINE: str = f"{VAR_CARD_TYPE_TAG}_NINE"
VAR_CARD_TYPE_TEN: str = f"{VAR_CARD_TYPE_TAG}_TEN"
VAR_CARD_TYPE_JACK: str = f"{VAR_CARD_TYPE_TAG}_JACK"
VAR_CARD_TYPE_QUEEN: str = f"{VAR_CARD_TYPE_TAG}_QUEEN"
VAR_CARD_TYPE_KING: str = f"{VAR_CARD_TYPE_TAG}_KING"
VAR_CARD_TYPE_ACE: str = f"{VAR_CARD_TYPE_TAG}_ACE"

# Card location variables:
VAR_CARD_LOCATION_TAG: str = "CARD_LOCATION"
VAR_CARD_LOCATION_NOT_SET: str = f"{VAR_CARD_LOCATION_TAG}_NOTSET"
VAR_CARD_LOCATION_HAND: str = f"{VAR_CARD_LOCATION_TAG}_HAND"
VAR_CARD_LOCATION_TABLE: str = f"{VAR_CARD_LOCATION_TAG}_TABLE"
VAR_CARD_LOCATION_DECK: str = f"{VAR_CARD_LOCATION_TAG}_DECK"
VAR_CARD_LOCATION_DISCARD: str = f"{VAR_CARD_LOCATION_TAG}_DISCARD"

# Card texture pack variables:
VAR_CARD_TEXTURE_PACK_TAG: str = "CARD_TEXTURE_PACK_TAG"
VAR_CARD_TEXTURE_PACK_DEFAULT: str = f"{VAR_CARD_TEXTURE_PACK_TAG}_DEFAULT"
