"""
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
TEXTURE PACK VARIABLES

"""

# Texture pack type variables:
TEXTURE_PACK_TYPE_TAG: str = "TEXTURE_PACK_TYPE"
TEXTURE_PACK_TYPE_FRONT: str = f"{TEXTURE_PACK_TYPE_TAG}_FRONT"
TEXTURE_PACK_TYPE_BACK: str = f"{TEXTURE_PACK_TYPE_TAG}_BACK"

# Texture pack mode variables:
TEXTURE_PACK_MODE_TAG: str = "TEXTURE_PACK_MODE"
TEXTURE_PACK_MODE_LIGHT: str = f"{TEXTURE_PACK_MODE_TAG}_LIGHT"
TEXTURE_PACK_MODE_DARK: str = f"{TEXTURE_PACK_MODE_TAG}_DARK"

# Texture pack (front) variables:
TEXTURE_PACK_FRONT_STYLE_DARK: str = "DARK"
TEXTURE_PACK_FRONT_STYLE_LIGHT: str = "LIGHT"
TEXTURE_PACK_FRONT_STYLE_SEPIA: str = "SEPIA"
TEXTURE_PACK_FRONT_COLOR_MONO: str = "MONO"
TEXTURE_PACK_FRONT_COLOR_DUO: str = "DUO"
TEXTURE_PACK_FRONT_COLOR_QUAD: str = "QUAD"

# Texture pack (back) variables:
TEXTURE_PACK_BACK_STYLE_CROSS: str = "CROSS"
TEXTURE_PACK_BACK_STYLE_MOUNTAINS: str = "MOUNTAINS"
TEXTURE_PACK_BACK_STYLE_PLAIN: str = "PLAIN"
TEXTURE_PACK_BACK_STYLE_SUN: str = "SUN"
TEXTURE_PACK_BACK_COLOR_BLUE: str = "BLUE"
TEXTURE_PACK_BACK_COLOR_GREEN: str = "GREEN"
TEXTURE_PACK_BACK_COLOR_NAVY: str = "NAVY"
TEXTURE_PACK_BACK_COLOR_ORANGE: str = "ORANGE"
TEXTURE_PACK_BACK_COLOR_PURPLE: str = "PURPLE"
TEXTURE_PACK_BACK_COLOR_RED: str = "RED"
TEXTURE_PACK_BACK_COLOR_WHITE: str = "WHITE"


"""
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
CARD VARIBALES

"""


# Suit variables:
CARD_SUIT_TAG: str = "SUIT"
CARD_SUIT_NOT_SET: str = f"{CARD_SUIT_TAG}_NOT_SET"
CARD_SUIT_HEARTS: str = f"{CARD_SUIT_TAG}_HEARTS"
CARD_SUIT_DIAMONDS: str = f"{CARD_SUIT_TAG}_DIAMONDS"
CARD_SUIT_CLUBS: str = f"{CARD_SUIT_TAG}_CLUBS"
CARD_SUIT_SPADES: str = f"{CARD_SUIT_TAG}_SPADES"

# Suit color variables:
CARD_SUIT_COLOR_TAG: str = "SUIT_COLOR"
CARD_SUIT_COLOR_NOT_SET: str = f"{CARD_SUIT_COLOR_TAG}_NOT_SET"
CARD_SUIT_COLOR_RED: str = f"{CARD_SUIT_COLOR_TAG}_RED"
CARD_SUIT_COLOR_BLACK: str = f"{CARD_SUIT_COLOR_TAG}_BLACK"

# Type variables:
CARD_TYPE_TAG: str = "CARD_TYPE"
CARD_TYPE_NOT_SET: str = f"{CARD_TYPE_TAG}_NOT_SET"
CARD_TYPE_TWO: str = f"{CARD_TYPE_TAG}_TWO"
CARD_TYPE_THREE: str = f"{CARD_TYPE_TAG}_THREE"
CARD_TYPE_FOUR: str = f"{CARD_TYPE_TAG}_FOUR"
CARD_TYPE_FIVE: str = f"{CARD_TYPE_TAG}_FIVE"
CARD_TYPE_SIX: str = f"{CARD_TYPE_TAG}_SIX"
CARD_TYPE_SEVEN: str = f"{CARD_TYPE_TAG}_SEVEN"
CARD_TYPE_EIGHT: str = f"{CARD_TYPE_TAG}_EIGHT"
CARD_TYPE_NINE: str = f"{CARD_TYPE_TAG}_NINE"
CARD_TYPE_TEN: str = f"{CARD_TYPE_TAG}_TEN"
CARD_TYPE_JACK: str = f"{CARD_TYPE_TAG}_JACK"
CARD_TYPE_QUEEN: str = f"{CARD_TYPE_TAG}_QUEEN"
CARD_TYPE_KING: str = f"{CARD_TYPE_TAG}_KING"
CARD_TYPE_ACE: str = f"{CARD_TYPE_TAG}_ACE"

# Card location variables:
CARD_LOCATION_TAG: str = "CARD_LOCATION"
CARD_LOCATION_NOT_SET: str = f"{CARD_LOCATION_TAG}_NOT_SET"
CARD_LOCATION_HAND: str = f"{CARD_LOCATION_TAG}_HAND"
CARD_LOCATION_DECK: str = f"{CARD_LOCATION_TAG}_DECK"
CARD_LOCATION_DISCARD: str = f"{CARD_LOCATION_TAG}_DISCARD"
CARD_LOCATION_TABLE: str = f"{CARD_LOCATION_TAG}_TABLE"


"""
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
PLAYER VARIBALES

"""


# Player type variables:
PLAYER_TYPE_TAG: str = "PLAYER_TYPE"
PLAYER_TYPE_NOT_SET: str = f"{PLAYER_TYPE_TAG}_NOT_SET"
PLAYER_TYPE_PLAYER: str = f"{PLAYER_TYPE_TAG}_PLAYER"
PLAYER_TYPE_COMPUTER: str = f"{PLAYER_TYPE_TAG}_COMPUTER"

# Player name variables:
PLAYER_ONE_NAME_DEFAULT: str = "Player"
PLAYER_TWO_NAME_DEFAULT: str = "Computer"

# Player state variables:
PLAYER_STATE_FOCUS_TAG: str = "PLAYER_STATE_FOCUS"
PLAYER_STATE_FOCUS_ATTACKING: str = f"{PLAYER_STATE_FOCUS_TAG}_ATTACKING"
PLAYER_STATE_FOCUS_DEFENDING: str = f"{PLAYER_STATE_FOCUS_TAG}_DEFENDING"